# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8efc411a0b3bd3b724e6a2aa2aca9b15d6b7647df03f27922b4c74dbf734dd882ddde171f25403419293b19788d647326b1a9757a33fa240f10a469a0d2cf179

test:
  secret_key_base: 708384115c99dce35ccebec15e085fd28dc55848359242bd688b8f7f63c827fec43e34d680192f5a521c0dc3252cf5c046b87f194954fb54b308c990408bf568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
